version: '3.5'

services:
  api:
    container_name: datingapp_container
    image: toyeebadesokan/dating_app:1.1
    ports:
      - "5555:80"
    networks:
      - datingapp-net
    restart: unless-stopped

networks:
  datingapp-net:
    driver: bridge
